Fg interfaces
cycloidio/sqlr pull request #1
Opened 2020-10-13 10:51 UTC by xescugc

This PR adds the default documentation of the usecases this lib fulfills

2020-10-13 13:41 UTC, patrislav reviewed
Would it make sense to include `golang/mock` mocks for the interfaces in this repository? Or do we expect the library consumers to generate them?

2020-10-13 14:26 UTC, xescugc commented
> It'd also force us to have unnatural SQL queries, where actual entity fields are at the end of the query (you cannot use the variadic at the beginning or in the middle).

That is a really good question that I don't have any preference or strong opinion, I would say that the caller is the one to do it just because it may not be using `gomock`, so it's up to the caller/user to do it.

OFC if we where to use it on this lib then yes but it's not the case.

2020-10-14 08:39 UTC, patrislav commented
> That is a really good question that I don't have any preference or strong opinion, I would say that the caller is the one to do it just because it may not be using `gomock`, so it's up to the caller/user to do it.
> 
> OFC if we where to use it on this lib then yes but it's not the case.

I see the reason to not have it, still, it'd be very useful for a user of the library who wants to mock those interfaces. IMO it'd add value. But we can discuss it in another issue, this PR LGTM :+1:

2020-10-14 08:40 UTC, kerak19 commented
I think that the interface definition maybe should be shown along with the description.

So for example

## Scanner

Used to abstract the logic of Scanning for `sql.Row` and `sql.Rows`.
```go
type Scanner interface {
	Scan(dest ...interface{}) error
}
```
Example usage
```go
func scanUsers(rows *sql.Rows) ([]*user.User, error) {
    users := make([]*user.User, 0,0)
    defer rows.Close()
    for rows.Next() {
        u, err := scanUser(rows)
        if err != nil {
            return nil, err
        }
        users = append(users, u)
    }
    if err := rows.Err(); err != nil {
        return nil, err
    }
    return users, nil
}

// Here goes the sqlr.Scanner
func scanUser(s sqlr.Scanner) (*user.User,error) {
    var u user.User
    err := s.Scan(
        &u.Name,
    )
    if err != nil {
        return nil, err
    }
    return u, nil
}
```

Single example containing all the interfaces may be too long (for now it's only two, but it may change)

2020-10-14 08:41 UTC, codebien requested changes
Just a very small thing

2020-10-14 08:41 UTC, codebien commented on querier.go
> +// RowQuerier requests a row in specific context
```suggestion
// RowQuerier requests a row in a specific context
```
Executer has already this form so I suggest moving to it for the rest

2020-10-14 14:12 UTC, xescugc commented
ok pushed the 2 changes.

2020-10-14 14:15 UTC, codebien commented
LGTM RS when others say too

2020-10-14 14:26 UTC, kerak19 reviewed
Hmm, there's no example for `Querier`, but IDK if that's necessary.

The formatting of the code is not `Go`-ish, should we fix that?

2020-10-14 15:58 UTC, xescugc commented
Done and RS

2020-10-14 15:59 UTC, kerak19 approved these changes

2020-10-14 16:04 UTC, codebien approved these changes

2020-10-14 16:10 UTC, merged